language: java

jdk:
- oraclejdk8
- openjdk7

services:
  - mysql
  
sudo: true

before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS ejercicio;'
- mysql -u root -e "GRANT ALL PRIVILEGES ON ejercicio.* TO 'travis'@'%';";

install: true
  
script: 
- mvn clean test
